workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    environment:
      node: 20
    scripts:
      - npm install
      - npx cap sync android
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      node: 20
      xcode: latest
    scripts:
      - npm install
      - npx cap sync ios
      - cd ios/App && pod install
    artifacts:
      - ios/App/build/**/*.ipa
